/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.codegen.analysis;

import com.datadoghq.reggie.codegen.ast.RegexNode;
import com.datadoghq.reggie.codegen.automaton.CharSet;
import java.util.List;

/**
 * Pattern information for SPECIALIZED_CONCAT_GREEDY_GROUP strategy.
 *
 * <p>Handles patterns with prefix + single greedy group + suffix: - a(b*) - x(y*)z - foo(bar+)baz -
 * prefix(pattern*)suffix
 *
 * <p>This strategy generates allocation-free bytecode that correctly handles zero-length group
 * captures (where group start == group end).
 */
public class ConcatGreedyGroupInfo implements PatternInfo {
  public final List<RegexNode> prefix; // Nodes before the group (literals, char classes)
  public final int groupNumber; // Capturing group number
  public final RegexNode quantifiedNode; // The node being quantified (inside the group)
  public final int minQuantifier; // Quantifier min (0 for *, 1 for +, n for {n,m})
  public final int maxQuantifier; // Quantifier max (Integer.MAX_VALUE for unbounded)
  public final List<RegexNode> suffix; // Nodes after the group
  public final CharSet quantifierCharSet; // Character set if quantified node is a char class
  public final String quantifierLiteral; // Literal string if quantified node is a literal

  public ConcatGreedyGroupInfo(
      List<RegexNode> prefix,
      int groupNumber,
      RegexNode quantifiedNode,
      int minQuantifier,
      int maxQuantifier,
      List<RegexNode> suffix,
      CharSet quantifierCharSet,
      String quantifierLiteral) {
    this.prefix = prefix;
    this.groupNumber = groupNumber;
    this.quantifiedNode = quantifiedNode;
    this.minQuantifier = minQuantifier;
    this.maxQuantifier = maxQuantifier;
    this.suffix = suffix;
    this.quantifierCharSet = quantifierCharSet;
    this.quantifierLiteral = quantifierLiteral;
  }

  /** Returns true if this is an unbounded greedy quantifier (*, +, {n,}). */
  public boolean isUnbounded() {
    return maxQuantifier == Integer.MAX_VALUE;
  }

  /** Returns true if the quantified element is a single literal character. */
  public boolean isLiteralQuantifier() {
    return quantifierLiteral != null && quantifierLiteral.length() == 1;
  }

  /** Returns true if the quantified element is a character class. */
  public boolean isCharClassQuantifier() {
    return quantifierCharSet != null;
  }

  /**
   * Compute structural hash for bytecode caching. Includes all structural elements that affect
   * generated bytecode.
   */
  @Override
  public int structuralHashCode() {
    int hash = getClass().getName().hashCode();
    hash = 31 * hash + prefix.size();
    hash = 31 * hash + suffix.size();
    hash = 31 * hash + minQuantifier;
    hash = 31 * hash + (isUnbounded() ? 1 : 0);
    hash = 31 * hash + (isLiteralQuantifier() ? 1 : 0);
    hash = 31 * hash + (isCharClassQuantifier() ? 2 : 0);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ConcatGreedyGroup[");
    sb.append("prefix=").append(prefix.size()).append(" nodes, ");
    sb.append("group=").append(groupNumber).append(", ");
    sb.append("quantifier={").append(minQuantifier).append(",").append(maxQuantifier).append("}, ");
    sb.append("suffix=").append(suffix.size()).append(" nodes");
    if (quantifierLiteral != null) {
      sb.append(", literal='").append(quantifierLiteral).append("'");
    }
    if (quantifierCharSet != null) {
      sb.append(", charset");
    }
    sb.append("]");
    return sb.toString();
  }
}
