/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.codegen.analysis;

import com.datadoghq.reggie.codegen.ast.*;

/**
 * Pattern info for RECURSIVE_DESCENT strategy. Computes structural hash including AST structure
 * with quantifier bounds and greedy flags, which are embedded directly in the generated bytecode.
 */
public class RecursiveDescentPatternInfo implements PatternInfo {

  private final RegexNode ast;
  private final int cachedHash;

  public RecursiveDescentPatternInfo(RegexNode ast) {
    this.ast = ast;
    this.cachedHash = computeASTStructuralHash(ast);
  }

  public RegexNode getAst() {
    return ast;
  }

  @Override
  public int structuralHashCode() {
    return cachedHash;
  }

  private static int computeASTStructuralHash(RegexNode ast) {
    if (ast == null) {
      return 0;
    }
    return ast.accept(new ASTStructuralHashVisitor());
  }

  /**
   * Visitor that computes structural hash for AST nodes. Includes all properties that affect
   * bytecode generation: - Node types - Quantifier min/max/greedy (CRITICAL for correct caching) -
   * Group types and numbers - CharClass negation and range count - Anchor and assertion types
   */
  private static class ASTStructuralHashVisitor implements RegexVisitor<Integer> {

    @Override
    public Integer visitLiteral(LiteralNode node) {
      int hash = 1;
      hash = 31 * hash + "Literal".hashCode();
      // Single character literal - include constant hash
      hash = 31 * hash + 1;
      return hash;
    }

    @Override
    public Integer visitCharClass(CharClassNode node) {
      int hash = 2;
      hash = 31 * hash + "CharClass".hashCode();
      hash = 31 * hash + (node.negated ? 1 : 0);
      // Include range count from CharSet
      hash = 31 * hash + node.chars.getRanges().size();
      return hash;
    }

    @Override
    public Integer visitConcat(ConcatNode node) {
      int hash = 3;
      hash = 31 * hash + "Concat".hashCode();
      hash = 31 * hash + node.children.size();
      for (RegexNode child : node.children) {
        hash = 31 * hash + child.accept(this);
      }
      return hash;
    }

    @Override
    public Integer visitAlternation(AlternationNode node) {
      int hash = 4;
      hash = 31 * hash + "Alternation".hashCode();
      hash = 31 * hash + node.alternatives.size();
      for (RegexNode alt : node.alternatives) {
        hash = 31 * hash + alt.accept(this);
      }
      return hash;
    }

    @Override
    public Integer visitQuantifier(QuantifierNode node) {
      int hash = 5;
      hash = 31 * hash + "Quantifier".hashCode();
      // CRITICAL: Include min, max, greedy - these affect bytecode behavior
      hash = 31 * hash + node.min;
      hash = 31 * hash + node.max;
      hash = 31 * hash + (node.greedy ? 1 : 0);
      hash = 31 * hash + node.child.accept(this);
      return hash;
    }

    @Override
    public Integer visitGroup(GroupNode node) {
      int hash = 6;
      hash = 31 * hash + "Group".hashCode();
      hash = 31 * hash + (node.capturing ? 1 : 0);
      hash = 31 * hash + node.groupNumber;
      if (node.child != null) {
        hash = 31 * hash + node.child.accept(this);
      }
      return hash;
    }

    @Override
    public Integer visitAnchor(AnchorNode node) {
      int hash = 7;
      hash = 31 * hash + "Anchor".hashCode();
      hash = 31 * hash + node.type.hashCode();
      return hash;
    }

    @Override
    public Integer visitBackreference(BackreferenceNode node) {
      int hash = 8;
      hash = 31 * hash + "Backref".hashCode();
      hash = 31 * hash + node.groupNumber;
      return hash;
    }

    @Override
    public Integer visitAssertion(AssertionNode node) {
      int hash = 9;
      hash = 31 * hash + "Assertion".hashCode();
      hash = 31 * hash + node.type.hashCode();
      if (node.subPattern != null) {
        hash = 31 * hash + node.subPattern.accept(this);
      }
      return hash;
    }

    @Override
    public Integer visitSubroutine(SubroutineNode node) {
      int hash = 10;
      hash = 31 * hash + "Subroutine".hashCode();
      hash = 31 * hash + node.groupNumber;
      return hash;
    }

    @Override
    public Integer visitConditional(ConditionalNode node) {
      int hash = 11;
      hash = 31 * hash + "Conditional".hashCode();
      hash = 31 * hash + node.condition;
      if (node.thenBranch != null) {
        hash = 31 * hash + node.thenBranch.accept(this);
      }
      if (node.elseBranch != null) {
        hash = 31 * hash + node.elseBranch.accept(this);
      }
      return hash;
    }

    @Override
    public Integer visitBranchReset(BranchResetNode node) {
      int hash = 12;
      hash = 31 * hash + "BranchReset".hashCode();
      hash = 31 * hash + node.alternatives.size();
      for (RegexNode alt : node.alternatives) {
        hash = 31 * hash + alt.accept(this);
      }
      return hash;
    }
  }
}
