version: 2
updates:
- package-ecosystem: gradle
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  groups:
    gradle-minor:
      update-types:
      - minor
      - patch
  cooldown:
    default-days: 14
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  cooldown:
    default-days: 14
