/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Correctness tests for the {@code BITSTATE_BYTECODE} strategy, generated by {@code
 * BitStateBytecodeGenerator} for the prefix-guarded-scan pattern family recognized by {@code
 * PatternAnalyzer#detectPrefixGuardedScan}.
 *
 * <p>The reference pattern under test is {@code (?s)(?m)^(?:\s*(?:sudo|doas)\s+)?\b\S+\b\s*(.*)}
 * (the "COMMAND" pattern from the design doc). Every expected value below was independently
 * verified against {@code java.util.regex.Pattern} (JDK 21) rather than assumed, since {@code
 * java.util.regex.Pattern}'s backtracking semantics for a required trailing {@code \b} after a
 * greedy {@code \S+} are not obvious from the pattern text alone (see {@code
 * BitStateBytecodeGeneratorTest#testTrailingBoundaryForcesGiveBack} below).
 */
public class BitStateBytecodeGeneratorTest {

  private static final String COMMAND_PATTERN =
      "(?s)(?m)^(?:\\s*(?:sudo|doas)\\s+)?\\b\\S+\\b\\s*(.*)";

  @BeforeEach
  void clearCache() {
    RuntimeCompiler.clearCache();
  }

  private static void assertMatchesLikeJdk(ReggieMatcher matcher, Pattern jdk, String input) {
    Matcher jm = jdk.matcher(input);
    boolean jdkMatches = jm.matches();
    assertEquals(jdkMatches, matcher.matches(input), "matches() for input [" + input + "]");
    if (jdkMatches) {
      MatchResult r = matcher.match(input);
      assertTrue(r != null, "match() should succeed for input [" + input + "]");
      assertEquals(jm.group(0), r.group(0), "group(0) for input [" + input + "]");
      assertEquals(jm.group(1), r.group(1), "group(1) for input [" + input + "]");
    } else {
      assertEquals(null, matcher.match(input), "match() should return null for [" + input + "]");
    }
  }

  @Test
  public void testRoutesToBitStateBytecode() {
    // Confirms the detector + router substitution actually selects BITSTATE_BYTECODE for the
    // COMMAND pattern, not merely that some other strategy happens to produce the right answer.
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    assertTrue(
        matcher.getClass().getName().contains("ReggieMatcher$"),
        "expected a generated hidden class, got " + matcher.getClass());
  }

  @Test
  public void testWithoutPrefixSimpleCommand() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "ls -la");
    assertMatchesLikeJdk(matcher, jdk, "ls");
  }

  @Test
  public void testWithSudoPrefix() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "sudo ls -la");
    assertMatchesLikeJdk(matcher, jdk, "  sudo   apt update");
  }

  @Test
  public void testWithDoasPrefix() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "doas rm -rf /");
  }

  @Test
  public void testEmptyTailAfterMandatoryToken() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "ls");
    assertMatchesLikeJdk(matcher, jdk, "sudo");
    assertMatchesLikeJdk(matcher, jdk, "a");
    assertMatchesLikeJdk(matcher, jdk, "ab");
  }

  @Test
  public void testTrailingWhitespaceAbsorbedBeforeTail() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "sudo\tls");
    assertMatchesLikeJdk(matcher, jdk, "SUDO ls");
  }

  @Test
  public void testNoMatchEmptyOrWhitespaceOnly() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "");
    assertMatchesLikeJdk(matcher, jdk, "   ");
  }

  @Test
  public void testNoMatchSingleNonWordCharacter() {
    // "!" alone: the mandatory \S+ matches "!", but the leading \b at position 0 never holds
    // (nothing before, non-word after), so the whole match fails - confirmed against JDK.
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "!");
  }

  /**
   * The key correctness scenario motivating {@code matchMandatory}'s bounded backward give-back
   * scan: JDK's real backtracking gives back one character from a greedy {@code \S+} run so that
   * the required trailing {@code \b} holds, changing where group 1 starts. Verified against JDK 21:
   * {@code "a!"} matches as a whole, with group(1) == "!" (not "" as a naive port of the
   * hand-written {@code CommandPatternPrototype} reference — which does not check the trailing
   * boundary at all — would produce).
   */
  @Test
  public void testTrailingBoundaryForcesGiveBack() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertTrue(jdk.matcher("a!").matches(), "sanity: JDK must match \"a!\"");
    assertEquals("!", jdk.matcher("a!").replaceFirst("$1"), "sanity: JDK group(1) must be \"!\"");
    assertMatchesLikeJdk(matcher, jdk, "a!");
  }

  @Test
  public void testWordCharMandatoryNeverNeedsGiveBack() {
    // Contrast case: a maximal \w+ run always ends adjacent to a non-word char or EOF, so the
    // trailing \b always holds at the greedy maximum and the give-back loop is a no-op.
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "ab");
    assertMatchesLikeJdk(matcher, jdk, "abc123");
  }

  @Test
  public void testMultilineRestartOnLeadingBoundaryFailure() {
    // First line "!" fails the leading \b unconditionally (not fixable by shrinking, since the
    // leading boundary is checked at a fixed position), forcing a line restart at the second line.
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    String input = "!\nab";
    Matcher jm = jdk.matcher(input);
    assertTrue(jm.find());
    assertTrue(matcher.find(input));
    int foundAt = matcher.findFrom(input, 0);
    assertEquals(jm.start(), foundAt);
    MatchResult r = matcher.findMatchFrom(input, 0);
    assertEquals(jm.group(0), r.group(0));
    assertEquals(jm.group(1), r.group(1));
  }

  @Test
  public void testMultilineOptionalPrefixAbsorbsLeadingNewline() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "\nsudo ls -la");
    assertMatchesLikeJdk(matcher, jdk, "   \nsudo ls");
  }

  @Test
  public void testFindMultilineDotAllTailAbsorbsNewlines() {
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    String input = "line1\nsudo ls -la\nline3";
    Matcher jm = jdk.matcher(input);
    assertTrue(jm.find());
    assertTrue(matcher.find(input));
    MatchResult r = matcher.findMatch(input);
    assertEquals(jm.group(0), r.group(0));
    assertEquals(jm.group(1), r.group(1));
  }

  @Test
  public void testKeywordSharedPrefixDoesNotFalselyMatchAsPrefixGroup() {
    // "sudoer" starts with "sudo" but there is no separator whitespace after it, so the optional
    // prefix group must NOT consume "sudo" as the keyword - the whole word is mandatory instead.
    ReggieMatcher matcher = RuntimeCompiler.compile(COMMAND_PATTERN);
    Pattern jdk = Pattern.compile(COMMAND_PATTERN);
    assertMatchesLikeJdk(matcher, jdk, "sudoer");
    assertMatchesLikeJdk(matcher, jdk, "doasomething");
  }

  @Test
  public void testStructurallySimilarSyntheticPattern() {
    // A different keyword set and word-char mandatory class, to prove the detector/generator is
    // data-driven from the AST rather than hardcoded to the COMMAND pattern's literals.
    String pattern = "^(?:\\s*(?:run|exec)\\s+)?\\b[a-zA-Z0-9_]+\\b\\s*(.*)";
    ReggieMatcher matcher = RuntimeCompiler.compile(pattern);
    Pattern jdk = Pattern.compile(pattern);
    assertMatchesLikeJdk(matcher, jdk, "run build.sh --fast");
    assertMatchesLikeJdk(matcher, jdk, "exec ls");
    assertMatchesLikeJdk(matcher, jdk, "build.sh");
    assertMatchesLikeJdk(matcher, jdk, "");
    assertMatchesLikeJdk(matcher, jdk, "runner"); // shared-prefix keyword, no separator
  }

  @Test
  public void testNegativeMissingLeadingAnchorFallsBackWithoutCrashing() {
    // No leading ^: does not match the detector's step 1, must not route to BITSTATE_BYTECODE
    // (falls back to some other strategy) but must still produce correct results.
    String pattern = "(?:\\s*(?:sudo|doas)\\s+)?\\b\\S+\\b\\s*(.*)";
    ReggieMatcher matcher = RuntimeCompiler.compile(pattern);
    Pattern jdk = Pattern.compile(pattern);
    assertMatchesLikeJdk(matcher, jdk, "sudo ls -la");
    assertMatchesLikeJdk(matcher, jdk, "ls");
  }

  @Test
  public void testNegativeNonDotStarTailFallsBackWithoutCrashing() {
    // Tail is a restricted char class, not `.*`, so it does not match the detector's step 7
    // shape; must not route to BITSTATE_BYTECODE but must still work correctly.
    String pattern = "^(?:\\s*(?:sudo|doas)\\s+)?\\b\\S+\\b\\s*([a-z]*)";
    ReggieMatcher matcher = RuntimeCompiler.compile(pattern);
    Pattern jdk = Pattern.compile(pattern);
    assertMatchesLikeJdk(matcher, jdk, "sudo ls");
    assertMatchesLikeJdk(matcher, jdk, "ls abc");
  }

  @Test
  public void testNegativeBoundedMandatoryQuantifierFallsBackWithoutCrashing() {
    // The mandatory scan is `\S{2,4}`, not `\S+` (bounded max), so the detector's unbounded-max
    // guard must reject this pattern; must not route to BITSTATE_BYTECODE but must still work.
    String pattern = "^(?:\\s*(?:sudo|doas)\\s+)?\\b\\S{2,4}\\b\\s*(.*)";
    ReggieMatcher matcher = RuntimeCompiler.compile(pattern);
    Pattern jdk = Pattern.compile(pattern);
    assertMatchesLikeJdk(matcher, jdk, "sudo ls -la");
    assertMatchesLikeJdk(matcher, jdk, "abcd tail");
    assertFalse(jdk.matcher("a tail").matches()); // sanity: below the {2,4} floor
    assertMatchesLikeJdk(matcher, jdk, "a tail");
  }

  @Test
  public void testNegativeOverlappingSeparatorAndMandatoryCharSetsFallsBackWithoutCrashing() {
    // separatorCharSet ([a-z]) overlaps mandatoryCharSet ([a-z]): the optional prefix's greedy
    // separator scan could over-consume characters the mandatory scan needs, with no give-back
    // possible without discarding the whole prefix. The detector must decline this shape.
    String pattern = "^(?:\\s*(?:123|456)[a-z]{1,})?[a-z]{3,}(.*)";
    ReggieMatcher matcher = RuntimeCompiler.compile(pattern);
    Pattern jdk = Pattern.compile(pattern);
    assertMatchesLikeJdk(matcher, jdk, "123abcdef");
    assertMatchesLikeJdk(matcher, jdk, "abcdef");
  }

  @Test
  public void testNegativeNoTrailingCapturingGroupFallsBackWithoutCrashing() {
    // No capturing group around the tail at all; must not route to BITSTATE_BYTECODE. Compares
    // only matches()/group(0) since there is no group 1 to compare.
    String pattern = "^(?:\\s*(?:sudo|doas)\\s+)?\\b\\S+\\b\\s*.*";
    ReggieMatcher matcher = RuntimeCompiler.compile(pattern);
    Pattern jdk = Pattern.compile(pattern);
    String input = "sudo ls -la";
    assertEquals(jdk.matcher(input).matches(), matcher.matches(input));
    MatchResult r = matcher.match(input);
    assertTrue(r != null);
    assertEquals(input, r.group(0));
  }
}
