/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

import static org.junit.jupiter.api.Assertions.*;

import com.datadoghq.reggie.Reggie;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Concurrency stress test for DFA-backed matchers.
 *
 * <p>DFA-backed matchers are cached as a single shared instance in PATTERN_CACHE. The generated
 * bytecode uses only method-local variables — no instance fields are written during matching. This
 * test verifies: (1) the cache contract (same object returned on every compile() call), and (2) the
 * shared instance produces JDK-consistent results under concurrent use from many threads.
 */
public class DfaMatcherConcurrencyTest {

  // Simple alternation — guaranteed DFA_UNROLLED (no groups, no lookaround).
  private static final String DFA_PATTERN = "a|b";
  private static final String MATCHING_INPUT = "say a there";
  private static final String NON_MATCHING_INPUT = "xyz";
  private static final Pattern JDK = Pattern.compile(DFA_PATTERN);

  @BeforeEach
  @AfterEach
  public void clearCache() {
    Reggie.clearCache();
  }

  /**
   * Primary cache-contract test: compile() for a DFA pattern must return the same instance every
   * time. This is what makes the concurrent test below meaningful — we are testing genuine shared
   * use of a single object, not independent instances that happen to agree.
   */
  @Test
  public void testDfaCompileReturnsSameInstance() {
    ReggieMatcher first = Reggie.compile(DFA_PATTERN);
    ReggieMatcher second = Reggie.compile(DFA_PATTERN);
    assertFalse(
        first instanceof JavaRegexFallbackMatcher,
        DFA_PATTERN + " must use native DFA engine, not JDK fallback");
    assertSame(
        first,
        second,
        "DFA-backed Reggie.compile() must return the same cached instance for identical patterns");
  }

  /**
   * 16 threads share a single DFA matcher and concurrently call find() 2000 times each,
   * cross-checking every result against JDK. DFA matchers are thread-safe by construction —
   * generated bytecode uses only method-local variables.
   */
  @Test
  public void testConcurrentFindOnSharedDfaMatcher() throws Exception {
    int numThreads = 16;
    int iterationsPerThread = 2000;

    ReggieMatcher shared = Reggie.compile(DFA_PATTERN);
    assertFalse(
        shared instanceof JavaRegexFallbackMatcher, DFA_PATTERN + " must use native DFA engine");

    boolean jdkMatchExpected = JDK.matcher(MATCHING_INPUT).find();
    boolean jdkNoMatchExpected = JDK.matcher(NON_MATCHING_INPUT).find();

    AtomicInteger failures = new AtomicInteger(0);
    CountDownLatch startLatch = new CountDownLatch(numThreads);
    CountDownLatch doneLatch = new CountDownLatch(numThreads);
    ExecutorService pool = Executors.newFixedThreadPool(numThreads);

    for (int t = 0; t < numThreads; t++) {
      pool.submit(
          () -> {
            try {
              startLatch.countDown();
              startLatch.await();
              for (int i = 0; i < iterationsPerThread; i++) {
                boolean match = shared.find(MATCHING_INPUT);
                boolean noMatch = shared.find(NON_MATCHING_INPUT);
                if (match != jdkMatchExpected || noMatch != jdkNoMatchExpected) {
                  failures.incrementAndGet();
                }
              }
            } catch (Exception e) {
              failures.incrementAndGet();
            } finally {
              doneLatch.countDown();
            }
          });
    }

    assertTrue(doneLatch.await(30, TimeUnit.SECONDS), "Threads timed out");
    pool.shutdownNow();
    assertEquals(
        0,
        failures.get(),
        "Shared DFA matcher must produce JDK-consistent results under concurrent use");
  }
}
