/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

import static org.junit.jupiter.api.Assertions.*;

import com.datadoghq.reggie.codegen.ast.RegexNode;
import com.datadoghq.reggie.codegen.automaton.DFA;
import com.datadoghq.reggie.codegen.automaton.NFA;
import com.datadoghq.reggie.codegen.automaton.SubsetConstructor;
import com.datadoghq.reggie.codegen.automaton.ThompsonBuilder;
import com.datadoghq.reggie.codegen.parsing.RegexParser;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Analyzes the DFA structure and generated bytecode for pattern \d+ to understand why there are 2
 * loops instead of 1.
 */
public class DigitPlusDFAAnalysisTest {

  @BeforeEach
  void clearCache() {
    RuntimeCompiler.clearCache();
  }

  @Test
  public void analyzeDFAStructure() throws Exception {
    // Pattern: "\d+" - should generate 2-state DFA
    RegexParser parser = new RegexParser();
    RegexNode ast = parser.parse("\\d+");

    ThompsonBuilder nfaBuilder = new ThompsonBuilder();
    NFA nfa = nfaBuilder.build(ast, 0);

    SubsetConstructor constructor = new SubsetConstructor();
    DFA dfa = constructor.buildDFA(nfa);

    System.out.println("=== DFA Structure for \\d+ ===");
    System.out.println("Total states: " + dfa.getStateCount());
    System.out.println("Start state ID: " + dfa.getStartState().id);
    System.out.println("Start state accepting: " + dfa.getStartState().accepting);
    System.out.println();

    // Print each state
    for (DFA.DFAState state : dfa.getAllStates()) {
      System.out.println("State " + state.id + ":");
      System.out.println("  Accepting: " + state.accepting);
      System.out.println("  Transitions: " + state.transitions.size());

      for (var entry : state.transitions.entrySet()) {
        var charset = entry.getKey();
        var transition = entry.getValue();

        String selfLoop = (transition.target.id == state.id) ? " [SELF-LOOP]" : "";
        System.out.println("    [" + charset + "] -> State " + transition.target.id + selfLoop);
      }
      System.out.println();
    }

    // Verify expected structure
    assertEquals(2, dfa.getStateCount(), "\\d+ should generate exactly 2 states");
    assertFalse(
        dfa.getStartState().accepting,
        "Start state should NOT be accepting (+ requires at least 1 digit)");

    // Find the accepting state
    DFA.DFAState acceptState = null;
    for (DFA.DFAState state : dfa.getAllStates()) {
      if (state.accepting) {
        acceptState = state;
        break;
      }
    }
    assertNotNull(acceptState, "Should have one accepting state");

    // Check transitions
    System.out.println("Expected optimal structure:");
    System.out.println("  State 0 (start, non-accepting): [0-9] -> State 1");
    System.out.println("  State 1 (accepting): [0-9] -> State 1 (self-loop)");
    System.out.println();
    System.out.println("This should generate ONE tight loop in bytecode!");
    System.out.println("The accepting state should have a self-loop on [0-9].");
  }

  @Test
  public void analyzeBytecode() throws Exception {
    // Compile the pattern
    ReggieMatcher matcher = RuntimeCompiler.compile("\\d+");

    // Get the generated class
    Class<?> clazz = matcher.getClass();
    System.out.println("\n=== Generated Class for \\d+ ===");
    System.out.println("Class: " + clazz.getName());
    System.out.println();
    System.out.println("From bytecode analysis, we know:");
    System.out.println("  - TWO separate loops exist (offsets 76-111 and 114-153)");
    System.out.println("  - Each loop: bounds check + charAt() + range check + jump");
    System.out.println(
        "  - This suggests the code generator creates separate code blocks per state");
    System.out.println();
    System.out.println("ROOT CAUSE: DFAUnrolledBytecodeGenerator.generateMatchesAtStartMethod()");
    System.out.println("  generates SEPARATE labels and code blocks for each DFA state.");
    System.out.println("  Even when State 1 has a self-loop on [0-9], it's implemented as:");
    System.out.println("    State_1_label:");
    System.out.println("      check if accepting -> possibly return");
    System.out.println("      check pos < len");
    System.out.println("      ch = charAt(pos++)");
    System.out.println("      if ch in [0-9] goto State_1_label  // This creates the loop!");
    System.out.println();
    System.out.println("  But State 0 also has a transition [0-9] -> State 1:");
    System.out.println("    State_0_label:");
    System.out.println("      check pos < len");
    System.out.println("      ch = charAt(pos++)");
    System.out.println("      if ch in [0-9] goto State_1_label");
    System.out.println();
    System.out.println("  So we get TWO separate code blocks doing charAt + range check!");
  }

  @Test
  public void comparePatterns() throws Exception {
    String[] patterns = {"a", "a+", "\\d", "\\d+", "[0-9]+", "(\\d+)"};

    System.out.println("\n=== DFA State Counts for Different Patterns ===");
    for (String pattern : patterns) {
      try {
        RegexParser parser = new RegexParser();
        RegexNode ast = parser.parse(pattern);

        ThompsonBuilder nfaBuilder = new ThompsonBuilder();
        int groupCount = countGroups(pattern);
        NFA nfa = nfaBuilder.build(ast, groupCount);

        SubsetConstructor constructor = new SubsetConstructor();
        DFA dfa = constructor.buildDFA(nfa);

        System.out.printf(
            "%-10s : %d states, start accepting: %5s%n",
            pattern, dfa.getStateCount(), dfa.getStartState().accepting);
      } catch (Exception e) {
        System.out.printf("%-10s : ERROR - %s%n", pattern, e.getMessage());
      }
    }
  }

  private static int countGroups(String pattern) {
    int count = 0;
    boolean escaped = false;
    for (int i = 0; i < pattern.length(); i++) {
      char c = pattern.charAt(i);
      if (escaped) {
        escaped = false;
        continue;
      }
      if (c == '\\') {
        escaped = true;
      } else if (c == '(' && i + 1 < pattern.length() && pattern.charAt(i + 1) != '?') {
        count++;
      }
    }
    return count;
  }
}
