/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import com.datadoghq.reggie.Reggie;
import com.datadoghq.reggie.codegen.analysis.PatternAnalyzer;
import com.datadoghq.reggie.codegen.analysis.StrategyJdkClassifier;
import com.datadoghq.reggie.codegen.analysis.StrategyJdkClassifier.StrategyJdkClass;
import com.datadoghq.reggie.codegen.ast.RegexNode;
import com.datadoghq.reggie.codegen.automaton.NFA;
import com.datadoghq.reggie.codegen.automaton.ThompsonBuilder;
import com.datadoghq.reggie.codegen.parsing.RegexParser;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogRecord;
import java.util.logging.Logger;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Verifies the JDK-dependency classification and empirically confirms NATIVE matchers never build
 * the JDK rich-API delegate (no backstop warning). All former RICH_API_HYBRID strategies
 * (SPECIALIZED_LITERAL_ALTERNATION and FIXED_REPETITION_BACKREF) have been promoted to NATIVE.
 */
class HybridWarningTest {

  private final List<LogRecord> records = new CopyOnWriteArrayList<>();
  private Handler handler;
  private Logger compilerLogger;
  private Logger matcherLogger;

  @BeforeEach
  void setUp() {
    handler =
        new Handler() {
          @Override
          public void publish(LogRecord record) {
            records.add(record);
          }

          @Override
          public void flush() {}

          @Override
          public void close() {}
        };
    handler.setLevel(Level.ALL);
    compilerLogger = Logger.getLogger(RuntimeCompiler.class.getName());
    matcherLogger = Logger.getLogger(ReggieMatcher.class.getName());
    compilerLogger.addHandler(handler);
    matcherLogger.addHandler(handler);
    // Ensure a fresh compile (and a fresh once-per-pattern warning) each test.
    RuntimeCompiler.clearCache();
  }

  @AfterEach
  void tearDown() {
    compilerLogger.removeHandler(handler);
    matcherLogger.removeHandler(handler);
    records.clear();
  }

  private List<String> messages() {
    return records.stream().map(LogRecord::getMessage).toList();
  }

  private boolean anyContains(String needle) {
    return messages().stream().anyMatch(m -> m.contains(needle));
  }

  /** {@code (a)\1{8,}} resolves to FIXED_REPETITION_BACKREF (now NATIVE after promotion). */
  @Test
  void fixedRepetitionBackrefIsNativeAfterPromotion() {
    String pattern = "(a)\\1{8,}";
    assertEquals("FIXED_REPETITION_BACKREF", strategyOf(pattern));
    assertEquals(StrategyJdkClass.NATIVE, jdkClassOf(pattern));

    ReggieMatcher m = Reggie.compile(pattern);
    m.match("aaaaaaaaa"); // 9 chars: 1 capture + 8 backrefs
    m.findMatch("xaaaaaaaaa");
    m.findMatchFrom("xaaaaaaaaa", 0);

    assertFalse(anyContains("HYBRID matcher"));
    assertFalse(anyContains("classified NATIVE but built"));
  }

  /** {@code keyword1|keyword2|...} resolves to SPECIALIZED_LITERAL_ALTERNATION (now NATIVE). */
  @Test
  void literalAlternationIsNativeAfterPromotion() {
    String pattern = "alpha|bravo|charlie|delta|echo";
    assertEquals("SPECIALIZED_LITERAL_ALTERNATION", strategyOf(pattern));
    assertEquals(StrategyJdkClass.NATIVE, jdkClassOf(pattern));

    ReggieMatcher m = Reggie.compile(pattern);
    // Exercising the rich API must not trigger the JDK delegate backstop.
    m.match("alpha");
    m.findMatch("the echo is loud");
    m.findMatchFrom("bravo team", 0);

    assertFalse(anyContains("HYBRID matcher"));
    assertFalse(anyContains("classified NATIVE but built"));
  }

  /** {@code \d{3}-\d{3}-\d{4}} is a NATIVE strategy — no hybrid warning, no delegate backstop. */
  @Test
  void nativePatternLogsNoHybridWarning() {
    String pattern = "\\d{3}-\\d{3}-\\d{4}";
    assertEquals(StrategyJdkClass.NATIVE, jdkClassOf(pattern));

    ReggieMatcher m = Reggie.compile(pattern);
    // Exercise the rich API: a NATIVE matcher answers these from generated bytecode and must never
    // build the JDK delegate (which would fire the ReggieMatcher backstop warning).
    m.match("123-456-7890");
    m.findMatch("call 123-456-7890 now");
    m.findMatchFrom("123-456-7890", 0);

    assertFalse(anyContains("HYBRID matcher"));
    assertFalse(anyContains("classified NATIVE but built"));
  }

  /**
   * Empirical sweep: for one representative pattern per NATIVE strategy, exercising the rich API
   * must never trip the {@code jdkRichDelegate()} backstop warning. This is the empirical proof
   * that the NATIVE set really does generate its own rich methods.
   */
  @Test
  void nativeStrategiesNeverBuildJdkDelegate() {
    String[] nativePatterns = {
      "\\w+", // STATELESS_LOOP
      "(\\d+)", // SPECIALIZED_GREEDY_CHARCLASS
      "([a-z]+)@([a-z]+)\\.com", // SPECIALIZED_MULTI_GROUP_GREEDY
      "\\d{3}-\\d{3}-\\d{4}", // SPECIALIZED_FIXED_SEQUENCE
      "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}", // SPECIALIZED_BOUNDED_QUANTIFIERS
      "([a-z]{3}).*\\1", // LINEAR_BACKREFERENCE
      "<(\\w+)>.*</\\1>", // SPECIALIZED_BACKREFERENCE
      "abc", // DFA_UNROLLED
      "(.*)bar", // GREEDY_BACKTRACK
      "foo|bar|baz|qux|quux", // SPECIALIZED_LITERAL_ALTERNATION (promoted to NATIVE)
      "(a)\\1{8,}", // FIXED_REPETITION_BACKREF (promoted to NATIVE)
    };
    for (String p : nativePatterns) {
      assertEquals(
          StrategyJdkClass.NATIVE,
          jdkClassOf(p),
          () -> "expected NATIVE for pattern " + p + " (strategy " + strategyOf(p) + ")");
      ReggieMatcher m = Reggie.compile(p);
      try {
        m.match("");
        m.findMatch("");
        m.findMatchFrom("", 0);
      } catch (RuntimeException ignored) {
        // input-shape mismatches are irrelevant; we only care whether the delegate was built.
      }
    }
    assertFalse(
        anyContains("classified NATIVE but built"),
        () -> "a NATIVE-classified matcher built the java.util.regex rich-API delegate");
  }

  private static String strategyOf(String pattern) {
    return analyze(pattern).strategy.name();
  }

  private static StrategyJdkClass jdkClassOf(String pattern) {
    return StrategyJdkClassifier.classifyJdkDependency(analyze(pattern).strategy);
  }

  private static PatternAnalyzer.MatchingStrategyResult analyze(String pattern) {
    try {
      RegexParser parser = new RegexParser();
      RegexNode ast = parser.parse(pattern);
      NFA nfa = null;
      if (!PatternAnalyzer.requiresRecursiveDescent(ast)) {
        nfa = new ThompsonBuilder().build(ast, countGroups(pattern));
      }
      return new PatternAnalyzer(ast, nfa).analyzeAndRecommend();
    } catch (Exception e) {
      throw new RuntimeException("analyze failed for " + pattern, e);
    }
  }

  private static int countGroups(String pattern) {
    int count = 0;
    boolean escaped = false;
    for (int i = 0; i < pattern.length(); i++) {
      char c = pattern.charAt(i);
      if (escaped) {
        escaped = false;
        continue;
      }
      if (c == '\\') {
        escaped = true;
      } else if (c == '(' && (i + 1 >= pattern.length() || pattern.charAt(i + 1) != '?')) {
        count++;
      }
    }
    return count;
  }
}
