/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

/**
 * Static helpers for SPECIALIZED_BACKREFERENCE generated matchers. Called by generated bytecode via
 * INVOKESTATIC to provide MatchResult-returning methods without duplicating the search logic in
 * each generated class.
 */
public final class BackreferenceHelpers {

  private BackreferenceHelpers() {}

  /**
   * Finds the first occurrence of an HTML-tag-style backreference pattern starting at {@code
   * startPos}.
   *
   * <p>Matches patterns of the form: {@code openPrefix + (\w+) + openSuffix + .* + closePrefix + \1
   * + closeSuffix}
   *
   * @param input the string to search
   * @param startPos starting position for the search
   * @param openPrefixChar the character that starts the tag, e.g. {@code '<'}
   * @param openSuffixChar the character that ends the opening tag, e.g. {@code '>'}
   * @param closePrefixStr the string that starts the closing tag, e.g. {@code "</"}
   * @param closeSuffixChar the character that ends the closing tag, e.g. {@code '>'}
   * @return a {@link MatchResult} or {@code null} if no match was found
   */
  public static MatchResult findHtmlTagMatchFrom(
      String input,
      int startPos,
      int openPrefixChar,
      int openSuffixChar,
      String closePrefixStr,
      int closeSuffixChar) {
    if (input == null) return null;
    int len = input.length();
    for (int pos = startPos; pos < len; pos++) {
      if (input.charAt(pos) != openPrefixChar) continue;
      int group1Start = pos + 1;
      int group1End = group1Start;
      while (group1End < len && isWordChar(input.charAt(group1End))) group1End++;
      if (group1End == group1Start) continue;
      if (group1End >= len || input.charAt(group1End) != (char) openSuffixChar) continue;
      int group1Len = group1End - group1Start;
      int searchFrom = group1End + 1;
      // Look for closePrefix + tagname + closeSuffix
      while (searchFrom <= len - (closePrefixStr.length() + group1Len + 1)) {
        int closeIdx = input.indexOf(closePrefixStr, searchFrom);
        if (closeIdx < 0) break;
        int backrefStart = closeIdx + closePrefixStr.length();
        if (backrefStart + group1Len >= len) break;
        if (!input.regionMatches(backrefStart, input, group1Start, group1Len)) {
          searchFrom = closeIdx + 1;
          continue;
        }
        int afterBackref = backrefStart + group1Len;
        if (afterBackref >= len || input.charAt(afterBackref) != (char) closeSuffixChar) {
          searchFrom = closeIdx + 1;
          continue;
        }
        int matchEnd = afterBackref + 1;
        return new MatchResultImpl(
            input, new int[] {pos, group1Start}, new int[] {matchEnd, group1End}, 1);
      }
    }
    return null;
  }

  /**
   * Finds the first occurrence of a repeated-word backreference pattern starting at {@code
   * startPos}.
   *
   * <p>Matches patterns of the form: {@code (\w+) separator \1}, optionally bounded by word
   * boundaries.
   */
  public static MatchResult findRepeatedWordMatchFrom(
      String input, int startPos, boolean requireWordBoundary) {
    if (input == null) return null;
    int len = input.length();
    for (int pos = startPos; pos < len; pos++) {
      if (requireWordBoundary && pos > 0 && isWordChar(input.charAt(pos - 1))) continue;
      if (!isWordChar(input.charAt(pos))) continue;
      int group1Start = pos;
      int group1End = group1Start + 1;
      while (group1End < len && isWordChar(input.charAt(group1End))) group1End++;
      int group1Len = group1End - group1Start;
      // Skip whitespace separator
      int sepStart = group1End;
      while (sepStart < len && isWhitespace(input.charAt(sepStart))) sepStart++;
      if (sepStart == group1End) continue; // no whitespace
      // Check backreference
      if (sepStart + group1Len > len) continue;
      if (!input.regionMatches(sepStart, input, group1Start, group1Len)) continue;
      int matchEnd = sepStart + group1Len;
      if (requireWordBoundary && matchEnd < len && isWordChar(input.charAt(matchEnd))) continue;
      return new MatchResultImpl(
          input, new int[] {pos, group1Start}, new int[] {matchEnd, group1End}, 1);
    }
    return null;
  }

  /**
   * Finds the first occurrence of a quoted-attribute backreference pattern starting at {@code
   * startPos}.
   *
   * <p>Matches patterns of the form: {@code quoteChar + ([^quoteChar]+) + quoteChar + sep + \1 +
   * quoteChar}
   */
  public static MatchResult findAttributeMatchFrom(
      String input, int startPos, int quoteChar, String assignmentOp) {
    if (input == null) return null;
    int len = input.length();
    for (int pos = startPos; pos < len; pos++) {
      if (input.charAt(pos) != (char) quoteChar) continue;
      int group1Start = pos + 1;
      int group1End = input.indexOf((char) quoteChar, group1Start);
      if (group1End < 0 || group1End == group1Start) continue;
      int group1Len = group1End - group1Start;
      // Skip assignment op (may include whitespace around it)
      int afterQuote = group1End + 1;
      // skip optional whitespace
      while (afterQuote < len && isWhitespace(input.charAt(afterQuote))) afterQuote++;
      // match assignmentOp
      if (!input.startsWith(assignmentOp, afterQuote)) continue;
      int afterOp = afterQuote + assignmentOp.length();
      // skip optional whitespace
      while (afterOp < len && isWhitespace(input.charAt(afterOp))) afterOp++;
      // opening quote for second value
      if (afterOp >= len || input.charAt(afterOp) != (char) quoteChar) continue;
      int backrefStart = afterOp + 1;
      if (backrefStart + group1Len > len) continue;
      if (!input.regionMatches(backrefStart, input, group1Start, group1Len)) continue;
      int afterBackref = backrefStart + group1Len;
      if (afterBackref >= len || input.charAt(afterBackref) != (char) quoteChar) continue;
      int matchEnd = afterBackref + 1;
      return new MatchResultImpl(
          input, new int[] {pos, group1Start}, new int[] {matchEnd, group1End}, 1);
    }
    return null;
  }

  private static boolean isWordChar(char c) {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_';
  }

  private static boolean isWhitespace(char c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r';
  }
}
