/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Function;
import java.util.logging.Logger;

/**
 * Base class for all compile-time generated regex matchers. Annotate abstract methods returning
 * this type with @RegexPattern to generate optimized implementations.
 *
 * <p>Example:
 *
 * <pre>{@code
 * public abstract class MyPatterns {
 *     @RegexPattern("\\d{3}-\\d{3}-\\d{4}")
 *     public abstract ReggieMatcher phone();
 * }
 * }</pre>
 */
public abstract class ReggieMatcher extends com.datadoghq.reggie.ReggieMatcher {

  private static final Logger LOG = Logger.getLogger(ReggieMatcher.class.getName());

  // Fires the misclassification backstop warning (below) at most once per JVM, so a classification
  // bug is never completely silent yet never floods the log.
  private static final AtomicBoolean NATIVE_DELEGATE_WARNED = new AtomicBoolean(false);

  // Set true by the compiler (runtime or annotation-processor path) when this matcher's strategy
  // was classified NATIVE — i.e. it is expected to fully generate the rich MatchResult API and
  // never build the JDK delegate. If such a matcher ever reaches jdkRichDelegate(), that is a
  // StrategyJdkClassifier / generator-emission bug; we warn instead of failing silently.
  private boolean expectsNativeRichApi;

  protected final String pattern;

  // injected by RuntimeCompiler after instantiation
  protected Map<String, Integer> nameToIndex = Collections.emptyMap();

  protected void setNameToIndex(Map<String, Integer> map) {
    this.nameToIndex = map;
  }

  /** Returns true if this matcher embeds nameToIndex into its MatchResult returns directly. */
  boolean embedsNameMap() {
    return false;
  }

  /**
   * Marks this matcher as having been classified {@code NATIVE} by {@code StrategyJdkClassifier} —
   * its generator is expected to emit the full rich MatchResult API, so it must never build the JDK
   * delegate. Set by the compiler; if such a matcher ever reaches {@link #jdkRichDelegate()} the
   * backstop there warns about the classification/emission bug.
   */
  protected void markNativeRichApi() {
    this.expectsNativeRichApi = true;
  }

  // Reusable NFA state for allocation-free matching
  // These fields are initialized lazily by NFA-based matchers
  protected StateSet currentStates;
  protected StateSet nextStates;
  protected int[] epsilonWorklist;
  protected StateSet epsilonProcessed;
  protected int[] groupStarts;
  protected int[] groupEnds;
  protected int[][] configGroupStarts;
  protected int[][] configGroupEnds;
  protected int[] parentStateMap;
  protected int[] recursiveGroups;

  // Stateful iterators for efficient BitSet iteration
  // Pre-allocated to avoid allocation overhead in hot path
  protected StateSet.Iterator currentStatesIter;
  protected StateSet.Iterator nextStatesIter;
  protected StateSet.Iterator epsilonProcessedIter;

  // Lazily-compiled java.util.regex delegate used by the rich MatchResult API
  // (match/findMatch/findMatchFrom) for strategies whose generated bytecode implements only the
  // allocation-free boolean fast path. Compiled on first use from this matcher's own pattern() so
  // group spans are JDK-correct. Never used by the boolean methods (matches/find/findFrom).
  private java.util.regex.Pattern jdkRich;
  private boolean jdkRichUnsupported;

  protected ReggieMatcher(String pattern) {
    this.pattern = pattern;
  }

  /**
   * Returns the lazily-compiled {@link java.util.regex.Pattern} for this matcher's pattern, used to
   * back the rich MatchResult API. Constructs that {@code java.util.regex} cannot parse
   * (subroutines {@code (?1)}/{@code (?R)}, recursion, conditionals {@code (?(1)..)}, branch-reset
   * {@code (?|..)}) make this throw a clear {@link UnsupportedOperationException} rather than allow
   * a wrong group span to be returned silently.
   */
  private java.util.regex.Pattern jdkRichDelegate() {
    // Backstop (defense in depth): a matcher classified NATIVE should fully generate the rich
    // MatchResult API and never reach here. If one does, StrategyJdkClassifier and the generator's
    // method emission have drifted — warn once so the misclassification is never silent.
    if (expectsNativeRichApi && NATIVE_DELEGATE_WARNED.compareAndSet(false, true)) {
      LOG.warning(
          "Reggie matcher for pattern '"
              + pattern
              + "' was classified NATIVE but built the java.util.regex rich-API delegate; this is a"
              + " StrategyJdkClassifier/generator classification bug — group extraction is silently"
              + " using java.util.regex.");
    }
    if (jdkRichUnsupported) {
      throw richUnsupported(null);
    }
    java.util.regex.Pattern p = jdkRich;
    if (p == null) {
      try {
        p = java.util.regex.Pattern.compile(JavaRegexFallbackMatcher.toJdkCompatible(pattern));
      } catch (java.util.regex.PatternSyntaxException e) {
        jdkRichUnsupported = true;
        throw richUnsupported(e);
      }
      jdkRich = p;
    }
    return p;
  }

  private UnsupportedOperationException richUnsupported(Throwable cause) {
    return new UnsupportedOperationException(
        "group extraction not supported for this construct; use matches()/find(): " + pattern,
        cause);
  }

  /**
   * JDK-backed whole-input match. Mirrors {@link #match(String)} semantics: returns a {@link
   * MatchResult} with JDK-correct group spans iff the entire input matches, else {@code null}.
   */
  protected final MatchResult jdkMatch(String input) {
    java.util.regex.Matcher m = jdkRichDelegate().matcher(input);
    return m.matches() ? toMatchResult(input, m) : null;
  }

  /**
   * JDK-backed {@link #findMatch(String)}: first match anywhere in {@code input}, or {@code null}.
   */
  protected final MatchResult jdkFindMatch(String input) {
    return jdkFindMatchFrom(input, 0);
  }

  /** JDK-backed {@link #findMatchFrom(String, int)}: first match at or after {@code start}. */
  protected final MatchResult jdkFindMatchFrom(String input, int start) {
    java.util.regex.Matcher m = jdkRichDelegate().matcher(input);
    return m.find(start) ? toMatchResult(input, m) : null;
  }

  private MatchResult toMatchResult(String input, java.util.regex.Matcher m) {
    int gc = m.groupCount();
    int[] starts = new int[gc + 1];
    int[] ends = new int[gc + 1];
    for (int i = 0; i <= gc; i++) {
      starts[i] = m.start(i);
      ends[i] = m.end(i);
    }
    // Prefer the matcher's own name map (set by RuntimeCompiler) so group(name) works even when the
    // JDK Pattern was compiled from a syntactically-converted pattern; fall back to the JDK names.
    Map<String, Integer> names =
        nameToIndex.isEmpty() ? jdkRichDelegate().namedGroups() : nameToIndex;
    return new MatchResultImpl(input, starts, ends, gc, names);
  }

  /**
   * Initialize reusable NFA state. Called once by NFA-based matchers.
   *
   * @param stateCount number of NFA states
   * @param groupCount number of capturing groups (0 if none)
   */
  protected void initNFAState(int stateCount, int groupCount) {
    if (this.currentStates == null) {
      this.currentStates = new StateSet(stateCount);
      this.nextStates = new StateSet(stateCount);
      this.epsilonWorklist = new int[stateCount];
      this.epsilonProcessed = new StateSet(stateCount);

      // Pre-allocate stateful iterators for SWAR-optimized iteration
      this.currentStatesIter = this.currentStates.iterator();
      this.nextStatesIter = this.nextStates.iterator();
      this.epsilonProcessedIter = this.epsilonProcessed.iterator();

      this.groupStarts = new int[groupCount + 1];
      this.groupEnds = new int[groupCount + 1];
      if (groupCount > 0) {
        this.configGroupStarts = new int[stateCount][groupCount + 1];
        this.configGroupEnds = new int[stateCount][groupCount + 1];
        this.parentStateMap = new int[stateCount];
      }
    }
  }

  /** Initialize reusable state for recursive-descent matchers. */
  protected void initRecursiveState(int groupCount) {
    if (this.recursiveGroups == null) {
      this.recursiveGroups = new int[(groupCount + 1) * 2];
    }
  }

  /**
   * Tests whether the entire input string matches the pattern. This method is allocation-free.
   *
   * @param input the string to match
   * @return true if the entire string matches
   */
  public abstract boolean matches(String input);

  /**
   * Finds if the pattern occurs anywhere in the input string. This method is allocation-free.
   *
   * @param input the string to search
   * @return true if the pattern is found
   */
  public abstract boolean find(String input);

  /**
   * Finds the pattern starting at the given offset. This method is allocation-free.
   *
   * @param input the string to search
   * @param start the starting offset
   * @return the starting position of the match, or -1 if not found
   */
  public abstract int findFrom(String input, int start);

  /**
   * Tests whether the entire input string matches the pattern and returns the match result. Unlike
   * {@link #matches(String)}, this method allocates a MatchResult object if the match succeeds.
   *
   * @param input the string to match
   * @return the match result, or null if the entire string doesn't match
   * @throws UnsupportedOperationException if the pattern uses a construct that {@code
   *     java.util.regex} cannot parse and the generator did not provide a fast-path override
   */
  public MatchResult match(String input) {
    return jdkMatch(input);
  }

  /**
   * Tests whether a bounded region of the input matches the pattern (boolean check). The pattern
   * must match the <em>entire</em> region {@code [start, end)}, matching the region semantics of
   * {@link java.util.regex.Matcher#region(int, int)} followed by {@link
   * java.util.regex.Matcher#matches()}.
   *
   * <p>The default implementation delegates to {@link #matches(String)} over the extracted region
   * substring and therefore allocates a substring. Bytecode generators may override this method
   * with an allocation-free implementation.
   *
   * @param input the character sequence to match
   * @param start the start index (inclusive)
   * @param end the end index (exclusive)
   * @return true if the bounded region matches
   */
  public boolean matchesBounded(CharSequence input, int start, int end) {
    return matches(input.subSequence(start, end).toString());
  }

  /**
   * Tests whether a bounded region of the input matches the pattern and returns the match result.
   * The pattern must match the <em>entire</em> region {@code [start, end)}. The returned result's
   * spans are relative to the <em>original</em> input (i.e. shifted by {@code start}), and {@link
   * MatchResult#group(int)} returns substrings of the original input — matching the region
   * semantics of {@link java.util.regex.Matcher#region(int, int)} followed by {@link
   * java.util.regex.Matcher#matches()}.
   *
   * <p>The default implementation delegates to {@link #match(String)} over the extracted region
   * substring and shifts the resulting spans. Bytecode generators may override this method with an
   * allocation-free implementation.
   *
   * @param input the character sequence to match
   * @param start the start index (inclusive)
   * @param end the end index (exclusive)
   * @return the match result, or null if the bounded region doesn't match
   */
  public MatchResult matchBounded(CharSequence input, int start, int end) {
    String region = input.subSequence(start, end).toString();
    MatchResult r = match(region);
    if (r == null) {
      return null;
    }
    if (start == 0) {
      return r;
    }
    return shiftSpans(r, start, input.toString());
  }

  /**
   * Builds a copy of {@code r} with every group span shifted by {@code delta}, anchored to {@code
   * originalInput} so that {@link MatchResult#group(int)} returns substrings of the original input.
   * Unmatched groups (span {@code -1}) are preserved as {@code -1}. Named-group lookups are
   * preserved when the source result exposes them via {@code this.nameToIndex}.
   */
  private MatchResult shiftSpans(MatchResult r, int delta, String originalInput) {
    int groupCount = r.groupCount();
    int[] starts = new int[groupCount + 1];
    int[] ends = new int[groupCount + 1];
    for (int i = 0; i <= groupCount; i++) {
      int s = r.start(i);
      int e = r.end(i);
      starts[i] = s == -1 ? -1 : s + delta;
      ends[i] = e == -1 ? -1 : e + delta;
    }
    return new MatchResultImpl(originalInput, starts, ends, groupCount, nameToIndex);
  }

  /**
   * Finds if the pattern occurs anywhere in the input string and returns the match result. Unlike
   * {@link #find(String)}, this method allocates a MatchResult object if a match is found.
   *
   * @param input the string to search
   * @return the match result, or null if not found
   * @throws UnsupportedOperationException if the pattern uses a construct that {@code
   *     java.util.regex} cannot parse and the generator did not provide a fast-path override
   */
  public MatchResult findMatch(String input) {
    return jdkFindMatch(input);
  }

  /**
   * Finds the pattern starting at the given offset and returns the match result. Unlike {@link
   * #findFrom(String, int)}, this method allocates a MatchResult object if a match is found.
   *
   * @param input the string to search
   * @param start the starting offset
   * @return the match result, or null if not found
   * @throws UnsupportedOperationException if the pattern uses a construct that {@code
   *     java.util.regex} cannot parse and the generator did not provide a fast-path override
   */
  public MatchResult findMatchFrom(String input, int start) {
    return jdkFindMatchFrom(input, start);
  }

  /**
   * Tests whether the entire input string matches and stores group boundaries in caller-provided
   * arrays. Group 0 is the entire match; groups 1..n are capturing groups. Unmatched optional
   * groups are stored as {@code -1} in both arrays.
   *
   * <p>The default implementation delegates to {@link #match(String)} and therefore may allocate.
   * Bytecode generators can override this method to populate the arrays directly.
   *
   * @param input the string to match
   * @param groupStarts caller-provided array for group start offsets
   * @param groupEnds caller-provided array for group end offsets
   * @return true if the entire input matches; false otherwise, leaving arrays unchanged
   * @throws NullPointerException if any argument is null
   * @throws IndexOutOfBoundsException if the arrays are too small for the matched pattern's groups
   */
  public boolean matchInto(String input, int[] groupStarts, int[] groupEnds) {
    Objects.requireNonNull(input, "input");
    Objects.requireNonNull(groupStarts, "groupStarts");
    Objects.requireNonNull(groupEnds, "groupEnds");

    MatchResult match = match(input);
    if (match == null) {
      return false;
    }
    copyGroups(match, groupStarts, groupEnds);
    return true;
  }

  /**
   * Finds the first match and stores group boundaries in caller-provided arrays. Equivalent to
   * {@link #findMatchInto(String, int, int[], int[])} with {@code start == 0}.
   *
   * @param input the string to search
   * @param groupStarts caller-provided array for group start offsets
   * @param groupEnds caller-provided array for group end offsets
   * @return true if a match is found; false otherwise, leaving arrays unchanged
   */
  public boolean findMatchInto(String input, int[] groupStarts, int[] groupEnds) {
    return findMatchInto(input, 0, groupStarts, groupEnds);
  }

  /**
   * Finds a match starting at the given offset and stores group boundaries in caller-provided
   * arrays. Group 0 is the entire match; groups 1..n are capturing groups. Unmatched optional
   * groups are stored as {@code -1} in both arrays.
   *
   * <p>The default implementation delegates to {@link #findMatchFrom(String, int)} and therefore
   * may allocate. Bytecode generators can override this method to populate the arrays directly.
   *
   * @param input the string to search
   * @param start the starting offset
   * @param groupStarts caller-provided array for group start offsets
   * @param groupEnds caller-provided array for group end offsets
   * @return true if a match is found; false otherwise, leaving arrays unchanged
   * @throws NullPointerException if any array/input argument is null
   * @throws IndexOutOfBoundsException if the arrays are too small for the matched pattern's groups
   */
  public boolean findMatchInto(String input, int start, int[] groupStarts, int[] groupEnds) {
    Objects.requireNonNull(input, "input");
    Objects.requireNonNull(groupStarts, "groupStarts");
    Objects.requireNonNull(groupEnds, "groupEnds");

    MatchResult match = findMatchFrom(input, start);
    if (match == null) {
      return false;
    }
    copyGroups(match, groupStarts, groupEnds);
    return true;
  }

  protected static void copyGroups(MatchResult match, int[] groupStarts, int[] groupEnds) {
    int groups = match.groupCount();
    if (groupStarts.length <= groups || groupEnds.length <= groups) {
      throw new IndexOutOfBoundsException(
          "group arrays must have length at least " + (groups + 1) + " for this pattern");
    }
    for (int i = 0; i <= groups; i++) {
      groupStarts[i] = match.start(i);
      groupEnds[i] = match.end(i);
    }
  }

  /**
   * Finds the pattern starting at the given offset and stores match boundaries in the provided
   * array. This is an allocation-free alternative to findMatchFrom() for operations that only need
   * match positions (like literal replacements without backreferences).
   *
   * <p>This method is allocation-free and should be preferred over findMatchFrom() when MatchResult
   * object creation is not necessary.
   *
   * @param input the string to search
   * @param start the starting offset
   * @param bounds array to store match boundaries: bounds[0]=start, bounds[1]=end
   * @return true if a match was found (bounds[] populated), false otherwise (bounds[] unchanged)
   */
  public boolean findBoundsFrom(String input, int start, int[] bounds) {
    // Default implementation for backward compatibility
    // Bytecode generators should override this with optimized implementations
    MatchResult match = findMatchFrom(input, start);
    if (match == null) {
      return false;
    }
    bounds[0] = match.start();
    bounds[1] = match.end();
    return true;
  }

  /**
   * Replaces the first occurrence of the pattern with the replacement string. Backreferences ($0,
   * $1, etc.) in the replacement string are expanded.
   *
   * <p>Optimization: Returns original string reference when no match found (zero allocation).
   *
   * @param input the input string
   * @param replacement the replacement string (may contain $n backreferences)
   * @return the string with the first match replaced
   */
  public String replaceFirst(String input, String replacement) {
    MatchResult match = findMatch(input);
    if (match == null) {
      return input; // Zero allocation - return original reference
    }

    return input.substring(0, match.start())
        + expandReplacement(replacement, match)
        + input.substring(match.end());
  }

  /**
   * Replaces all occurrences of the pattern with the replacement string. Backreferences ($0, $1,
   * etc.) in the replacement string are expanded.
   *
   * <p>Optimization: Returns original string reference when no match found (zero allocation).
   *
   * @param input the input string
   * @param replacement the replacement string (may contain $n backreferences)
   * @return the string with all matches replaced
   */
  public String replaceAll(String input, String replacement) {
    // Fast path for literal replacements (no backreferences)
    if (replacement.indexOf('$') == -1) {
      return replaceAllLiteral(input, replacement);
    }

    // Slow path for replacements with backreferences
    List<MatchResult> matches = findAll(input);
    if (matches.isEmpty()) {
      return input; // Zero allocation - return original reference
    }

    StringBuilder result = new StringBuilder();
    int lastEnd = 0;

    for (MatchResult match : matches) {
      result.append(input, lastEnd, match.start());
      result.append(expandReplacement(replacement, match));
      lastEnd = match.end();
    }
    result.append(input, lastEnd, input.length());

    return result.toString();
  }

  /**
   * Replaces all occurrences with a literal replacement string (no backreferences). This is an
   * optimized path that avoids MatchResult allocations.
   *
   * @param input the input string
   * @param replacement the literal replacement string (no $ backreferences)
   * @return the string with all matches replaced
   */
  private String replaceAllLiteral(String input, String replacement) {
    int[] bounds = new int[2];
    int pos = 0;

    // Check if there's at least one match
    if (!findBoundsFrom(input, pos, bounds)) {
      return input; // Zero allocation - return original reference
    }

    StringBuilder result = new StringBuilder();
    int lastEnd = 0;

    do {
      result.append(input, lastEnd, bounds[0]);
      result.append(replacement);
      lastEnd = bounds[1];

      pos = advancePos(bounds[0], bounds[1]);
    } while (pos <= input.length() && findBoundsFrom(input, pos, bounds));

    result.append(input, lastEnd, input.length());
    return result.toString();
  }

  /**
   * Replaces all occurrences of the pattern using a function to compute replacements.
   *
   * @param input the input string
   * @param replacer function that takes a MatchResult and returns a replacement string
   * @return the string with all matches replaced
   */
  public String replaceAll(String input, Function<MatchResult, String> replacer) {
    StringBuilder result = new StringBuilder();
    int lastEnd = 0;

    for (MatchResult match : findAll(input)) {
      result.append(input, lastEnd, match.start());
      result.append(replacer.apply(match));
      lastEnd = match.end();
    }
    result.append(input, lastEnd, input.length());

    return result.toString();
  }

  /**
   * Splits the input string around matches of the pattern.
   *
   * <p>Equivalent to {@code split(input, 0)}: all parts are returned with trailing empty strings
   * discarded, matching the behaviour of {@link java.util.regex.Pattern#split(CharSequence)}.
   *
   * @param input the input string
   * @return array of strings split around matches
   * @throws NullPointerException if input is null
   */
  public String[] split(String input) {
    return split(input, 0);
  }

  /**
   * Splits the input string around matches of the pattern.
   *
   * <p>The {@code limit} parameter controls the number of parts returned and whether trailing empty
   * strings are discarded, matching the semantics of {@link
   * java.util.regex.Pattern#split(CharSequence, int)}:
   *
   * <ul>
   *   <li>{@code limit > 0} — at most {@code limit} parts; the last part contains the remainder of
   *       the string; trailing empty strings are retained.
   *   <li>{@code limit < 0} — all parts; trailing empty strings are retained.
   *   <li>{@code limit = 0} — all parts; trailing empty strings are discarded.
   * </ul>
   *
   * @param input the input string
   * @param limit controls the number of parts as described above
   * @return array of strings split around matches
   * @throws NullPointerException if input is null
   */
  public String[] split(String input, int limit) {
    Objects.requireNonNull(input);
    List<String> parts = new ArrayList<>();
    int lastEnd = 0;
    int pos = 0;

    while (pos <= input.length()) {
      // Early termination: we have limit - 1 parts, remainder becomes the last part.
      if (limit > 0 && parts.size() == limit - 1) {
        break;
      }

      MatchResult match = findMatchFrom(input, pos);
      if (match == null) {
        break;
      }

      // JDK 8+ behaviour: skip a zero-width match at the very start of the string.
      if (lastEnd == 0 && match.start() == 0 && match.start() == match.end()) {
        pos = 1;
        continue;
      }

      parts.add(input.substring(lastEnd, match.start()));
      lastEnd = match.end();

      // Advance past zero-width match to prevent an infinite loop.
      pos = advancePos(match.start(), match.end());
    }

    // No splits: return the whole input as a single-element array (matches JDK behaviour).
    if (lastEnd == 0) {
      return new String[] {input};
    }

    if (limit <= 0 || parts.size() < limit) {
      parts.add(input.substring(lastEnd));
    }

    if (limit == 0) {
      int size = parts.size();
      while (size > 0 && parts.get(size - 1).isEmpty()) {
        size--;
      }
      return parts.subList(0, size).toArray(new String[0]);
    }

    return parts.toArray(new String[0]);
  }

  /**
   * Finds all occurrences of the pattern in the input string.
   *
   * @param input the input string
   * @return list of all matches
   */
  public List<MatchResult> findAll(String input) {
    List<MatchResult> results = new ArrayList<>();
    int pos = 0;

    while (pos <= input.length()) {
      MatchResult match = findMatchFrom(input, pos);
      if (match == null) {
        break;
      }

      results.add(match);

      pos = advancePos(match.start(), match.end());
    }

    return results;
  }

  /**
   * Returns the next scan position after a match, advancing by one extra character for zero-width
   * matches to prevent an infinite loop.
   */
  private static int advancePos(int matchStart, int matchEnd) {
    return matchEnd + (matchStart == matchEnd ? 1 : 0);
  }

  /**
   * Expands backreferences ($0, $1, etc.) in the replacement string.
   *
   * @param replacement the replacement string
   * @param match the match result
   * @return the expanded replacement string
   */
  private String expandReplacement(String replacement, MatchResult match) {
    StringBuilder result = new StringBuilder();

    for (int i = 0; i < replacement.length(); i++) {
      char c = replacement.charAt(i);
      if (c == '$' && i + 1 < replacement.length()) {
        char next = replacement.charAt(i + 1);
        if (next >= '0' && next <= '9') {
          int groupNum = next - '0';
          if (groupNum <= match.groupCount()) {
            String groupValue = match.group(groupNum);
            if (groupValue != null) {
              result.append(groupValue);
            }
          } else {
            result.append(c).append(next);
          }
          i++; // skip digit
          continue;
        } else if (next == '$') {
          result.append('$');
          i++;
          continue;
        }
      }
      result.append(c);
    }
    return result.toString();
  }

  /** Creates a new MatchCursor for streaming replacement over the given input. */
  public MatchCursor cursor(String input) {
    Objects.requireNonNull(input, "input");
    return new MatchCursor(this, input);
  }

  /**
   * Gets the pattern string this matcher was generated for.
   *
   * @return the regex pattern
   */
  public final String pattern() {
    return pattern;
  }
}
