/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.runtime;

/**
 * Helper methods for SWAR-optimized pattern matching. These methods are called from generated
 * bytecode.
 */
public final class SWARHelper {

  private SWARHelper() {
    // Utility class
  }

  /**
   * Find next position in string that starts with a hex digit. Uses SWAR optimization for Latin-1
   * strings.
   *
   * <p>Called from generated bytecode for patterns that start with hex digit charset.
   *
   * @param input input string
   * @param fromIndex starting position
   * @param len string length
   * @return next position with hex digit, or -1 if none found
   */
  public static int findNextHexPosition(String input, int fromIndex, int len) {
    if (fromIndex >= len) {
      return -1;
    }

    if (!SWARUtils.isEnabled() || !StringView.isZeroCopyAvailable()) {
      // SWAR or StringView disabled - fallback to scalar scan
      return findNextHexPositionScalar(input, fromIndex, len);
    }

    StringView view = StringView.of(input);
    if (view == null || !view.isLatin1()) {
      // StringView creation failed or UTF-16 string - fallback
      return findNextHexPositionScalar(input, fromIndex, len);
    }

    // Delegate to StringView version
    return findNextHexPosition(view, fromIndex, len);
  }

  /**
   * Find next position in string that starts with a hex digit. Uses SWAR optimization for Latin-1
   * strings.
   *
   * <p>This version accepts a pre-created StringView, eliminating the overhead of repeated
   * StringView creation in tight loops.
   *
   * @param view StringView of the input string (must be non-null and Latin-1)
   * @param fromIndex starting position
   * @param len string length
   * @return next position with hex digit, or -1 if none found
   */
  public static int findNextHexPosition(StringView view, int fromIndex, int len) {
    if (fromIndex >= len || view == null || !view.isLatin1()) {
      return -1;
    }

    int result = view.findFirstHexDigit(fromIndex);
    return result >= 0 && result < len ? result : -1;
  }

  /** Scalar fallback for finding next hex position. */
  private static int findNextHexPositionScalar(String input, int fromIndex, int len) {
    for (int i = fromIndex; i < len; i++) {
      char c = input.charAt(i);
      if (isHexDigit(c)) {
        return i;
      }
    }
    return -1;
  }

  /** Check if character is a hex digit. */
  private static boolean isHexDigit(char c) {
    return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F');
  }

  /**
   * Find next position in string with a character in range [low, high]. Uses SWAR optimization for
   * Latin-1 strings.
   *
   * @param input input string
   * @param fromIndex starting position
   * @param len string length
   * @param low lower bound (inclusive)
   * @param high upper bound (inclusive)
   * @return next position with character in range, or -1 if none found
   */
  public static int findNextInRange(String input, int fromIndex, int len, int low, int high) {
    if (fromIndex >= len) {
      return -1;
    }

    if (!SWARUtils.isEnabled() || !StringView.isZeroCopyAvailable()) {
      return findNextInRangeScalar(input, fromIndex, len, (char) low, (char) high);
    }

    StringView view = StringView.of(input);
    if (view == null || !view.isLatin1()) {
      return findNextInRangeScalar(input, fromIndex, len, (char) low, (char) high);
    }

    // Delegate to StringView version
    return findNextInRange(view, fromIndex, len, low, high);
  }

  /**
   * Find next position in string with a character in range [low, high]. Uses SWAR optimization for
   * Latin-1 strings.
   *
   * <p>This version accepts a pre-created StringView, eliminating the overhead of repeated
   * StringView creation in tight loops.
   *
   * @param view StringView of the input string (must be non-null and Latin-1)
   * @param fromIndex starting position
   * @param len string length
   * @param low lower bound (inclusive)
   * @param high upper bound (inclusive)
   * @return next position with character in range, or -1 if none found
   */
  public static int findNextInRange(StringView view, int fromIndex, int len, int low, int high) {
    if (fromIndex >= len || view == null || !view.isLatin1()) {
      return -1;
    }

    int result =
        SWARUtils.findFirstInRange(
            view.getBytes(),
            view.getOffset() + fromIndex,
            view.getOffset() + len,
            (char) low,
            (char) high);

    return result >= 0 ? (result - view.getOffset()) : -1;
  }

  /** Scalar fallback for finding next position in range. */
  private static int findNextInRangeScalar(
      String input, int fromIndex, int len, char low, char high) {
    for (int i = fromIndex; i < len; i++) {
      char c = input.charAt(i);
      if (c >= low && c <= high) {
        return i;
      }
    }
    return -1;
  }

  /**
   * Find next position in string with a specific byte value. Uses SWAR optimization for Latin-1
   * strings.
   *
   * @param input input string
   * @param fromIndex starting position
   * @param len string length
   * @param target target byte to find
   * @return next position with target byte, or -1 if none found
   */
  public static int findNextByte(String input, int fromIndex, int len, int target) {
    if (fromIndex >= len) {
      return -1;
    }

    if (!SWARUtils.isEnabled() || !StringView.isZeroCopyAvailable()) {
      return findNextByteScalar(input, fromIndex, len, (byte) target);
    }

    StringView view = StringView.of(input);
    if (view == null || !view.isLatin1()) {
      return findNextByteScalar(input, fromIndex, len, (byte) target);
    }

    // Delegate to StringView version
    return findNextByte(view, fromIndex, len, target);
  }

  /**
   * Find next position in string with a specific byte value. Uses SWAR optimization for Latin-1
   * strings.
   *
   * <p>This version accepts a pre-created StringView, eliminating the overhead of repeated
   * StringView creation in tight loops.
   *
   * @param view StringView of the input string (must be non-null and Latin-1)
   * @param fromIndex starting position
   * @param len string length
   * @param target target byte to find
   * @return next position with target byte, or -1 if none found
   */
  public static int findNextByte(StringView view, int fromIndex, int len, int target) {
    if (fromIndex >= len || view == null || !view.isLatin1()) {
      return -1;
    }

    int result =
        SWARUtils.findFirstByte(
            view.getBytes(), view.getOffset() + fromIndex, view.getOffset() + len, (byte) target);

    return result >= 0 ? (result - view.getOffset()) : -1;
  }

  /** Scalar fallback for finding next byte. */
  private static int findNextByteScalar(String input, int fromIndex, int len, byte target) {
    for (int i = fromIndex; i < len; i++) {
      char c = input.charAt(i);
      if (c == (target & 0xFF)) {
        return i;
      }
    }
    return -1;
  }

  /**
   * Find next position in string with a character NOT in range [low, high]. Uses SWAR optimization
   * for Latin-1 strings.
   *
   * @param input input string
   * @param fromIndex starting position
   * @param len string length
   * @param low lower bound (inclusive)
   * @param high upper bound (inclusive)
   * @return next position with character not in range, or -1 if none found
   */
  public static int findNextNotInRange(String input, int fromIndex, int len, int low, int high) {
    if (fromIndex >= len) {
      return -1;
    }

    if (!SWARUtils.isEnabled() || !StringView.isZeroCopyAvailable()) {
      return findNextNotInRangeScalar(input, fromIndex, len, (char) low, (char) high);
    }

    StringView view = StringView.of(input);
    if (view == null || !view.isLatin1()) {
      return findNextNotInRangeScalar(input, fromIndex, len, (char) low, (char) high);
    }

    // Delegate to StringView version
    return findNextNotInRange(view, fromIndex, len, low, high);
  }

  /**
   * Find next position in string with a character NOT in range [low, high]. Uses SWAR optimization
   * for Latin-1 strings.
   *
   * <p>This version accepts a pre-created StringView, eliminating the overhead of repeated
   * StringView creation in tight loops.
   *
   * @param view StringView of the input string (must be non-null and Latin-1)
   * @param fromIndex starting position
   * @param len string length
   * @param low lower bound (inclusive)
   * @param high upper bound (inclusive)
   * @return next position with character not in range, or -1 if none found
   */
  public static int findNextNotInRange(StringView view, int fromIndex, int len, int low, int high) {
    if (fromIndex >= len || view == null || !view.isLatin1()) {
      return -1;
    }

    int result =
        SWARUtils.findFirstNotInRange(
            view.getBytes(),
            view.getOffset() + fromIndex,
            view.getOffset() + len,
            (char) low,
            (char) high);

    return result >= 0 ? (result - view.getOffset()) : -1;
  }

  /** Scalar fallback for finding next position not in range. */
  private static int findNextNotInRangeScalar(
      String input, int fromIndex, int len, char low, char high) {
    for (int i = fromIndex; i < len; i++) {
      char c = input.charAt(i);
      if (c < low || c > high) {
        return i;
      }
    }
    return -1;
  }

  /**
   * Find next position in string with an ASCII letter [a-zA-Z]. Uses SWAR optimization for Latin-1
   * strings.
   *
   * @param input input string
   * @param fromIndex starting position
   * @param len string length
   * @return next position with ASCII letter, or -1 if none found
   */
  public static int findNextAlpha(String input, int fromIndex, int len) {
    if (fromIndex >= len) {
      return -1;
    }

    if (!SWARUtils.isEnabled() || !StringView.isZeroCopyAvailable()) {
      return findNextAlphaScalar(input, fromIndex, len);
    }

    StringView view = StringView.of(input);
    if (view == null || !view.isLatin1()) {
      return findNextAlphaScalar(input, fromIndex, len);
    }

    // Delegate to StringView version
    return findNextAlpha(view, fromIndex, len);
  }

  /**
   * Find next position in string with an ASCII letter [a-zA-Z]. Uses SWAR optimization for Latin-1
   * strings.
   *
   * <p>This version accepts a pre-created StringView, eliminating the overhead of repeated
   * StringView creation in tight loops.
   *
   * @param view StringView of the input string (must be non-null and Latin-1)
   * @param fromIndex starting position
   * @param len string length
   * @return next position with ASCII letter, or -1 if none found
   */
  public static int findNextAlpha(StringView view, int fromIndex, int len) {
    if (fromIndex >= len || view == null || !view.isLatin1()) {
      return -1;
    }

    char[] ranges = {'a', 'z', 'A', 'Z'};
    int result =
        SWARUtils.findFirstInRanges(
            view.getBytes(), view.getOffset() + fromIndex, view.getOffset() + len, ranges);

    return result >= 0 ? (result - view.getOffset()) : -1;
  }

  /** Scalar fallback for finding next ASCII letter. */
  private static int findNextAlphaScalar(String input, int fromIndex, int len) {
    for (int i = fromIndex; i < len; i++) {
      char c = input.charAt(i);
      if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')) {
        return i;
      }
    }
    return -1;
  }

  /**
   * Find next position in string with an alphanumeric character [a-zA-Z0-9]. Uses SWAR optimization
   * for Latin-1 strings.
   *
   * @param input input string
   * @param fromIndex starting position
   * @param len string length
   * @return next position with alphanumeric character, or -1 if none found
   */
  public static int findNextAlphaNum(String input, int fromIndex, int len) {
    if (fromIndex >= len) {
      return -1;
    }

    if (!SWARUtils.isEnabled() || !StringView.isZeroCopyAvailable()) {
      return findNextAlphaNumScalar(input, fromIndex, len);
    }

    StringView view = StringView.of(input);
    if (view == null || !view.isLatin1()) {
      return findNextAlphaNumScalar(input, fromIndex, len);
    }

    // Delegate to StringView version
    return findNextAlphaNum(view, fromIndex, len);
  }

  /**
   * Find next position in string with an alphanumeric character [a-zA-Z0-9]. Uses SWAR optimization
   * for Latin-1 strings.
   *
   * <p>This version accepts a pre-created StringView, eliminating the overhead of repeated
   * StringView creation in tight loops.
   *
   * @param view StringView of the input string (must be non-null and Latin-1)
   * @param fromIndex starting position
   * @param len string length
   * @return next position with alphanumeric character, or -1 if none found
   */
  public static int findNextAlphaNum(StringView view, int fromIndex, int len) {
    if (fromIndex >= len || view == null || !view.isLatin1()) {
      return -1;
    }

    char[] ranges = {'0', '9', 'a', 'z', 'A', 'Z'};
    int result =
        SWARUtils.findFirstInRanges(
            view.getBytes(), view.getOffset() + fromIndex, view.getOffset() + len, ranges);

    return result >= 0 ? (result - view.getOffset()) : -1;
  }

  /** Scalar fallback for finding next alphanumeric character. */
  private static int findNextAlphaNumScalar(String input, int fromIndex, int len) {
    for (int i = fromIndex; i < len; i++) {
      char c = input.charAt(i);
      if ((c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')) {
        return i;
      }
    }
    return -1;
  }

  /**
   * Count consecutive matches of a single character starting from a position. Uses scalar
   * implementation for now (SWAR TODO for future optimization).
   *
   * @param input input string
   * @param start starting position
   * @param len string length
   * @param target character to match
   * @return number of consecutive matches from start position
   */
  public static int countMatchingSingleByte(String input, int start, int len, char target) {
    int count = 0;
    int pos = start;

    while (pos < len) {
      char c = input.charAt(pos);
      if (c != target) {
        break;
      }
      count++;
      pos++;
    }

    return count;
  }

  /**
   * Count consecutive matches in a character range [min, max] starting from a position. Uses scalar
   * implementation for now (SWAR TODO for future optimization).
   *
   * @param input input string
   * @param start starting position
   * @param len string length
   * @param min lower bound (inclusive)
   * @param max upper bound (inclusive)
   * @return number of consecutive matches from start position
   */
  public static int countMatchingRange(String input, int start, int len, char min, char max) {
    int count = 0;
    int pos = start;

    while (pos < len) {
      char c = input.charAt(pos);
      if (c < min || c > max) {
        break;
      }
      count++;
      pos++;
    }

    return count;
  }
}
