blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/DataDog/java-reggie/security/advisories/new
    about: Report security vulnerabilities privately (do NOT open a public issue)
