/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.codegen.codegen.swar;

import static org.objectweb.asm.Opcodes.*;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;

/**
 * Base class for SWAR optimizations in bytecode generation.
 *
 * <p>Each subclass represents a specific pattern type that can benefit from SWAR optimization and
 * knows how to generate the specialized bytecode for finding matching positions.
 *
 * <p>The optimization decision is made at compile time - if a pattern is SWAR-optimizable, the
 * corresponding subclass generates specialized bytecode with zero runtime overhead.
 */
public abstract class SWAROptimization {

  /**
   * Generate bytecode to find the next matching position in the input string.
   *
   * <p>The generated bytecode should: 1. Call the appropriate SWARHelper method 2. Store the result
   * back to the start variable 3. Handle the case where no match is found (result == -1)
   *
   * <p>Stack state before: (unchanged) Stack state after: (unchanged)
   *
   * @param mv the method visitor for bytecode generation
   * @param inputVarSlot local variable slot containing the input String
   * @param startVarSlot local variable slot containing the start position (will be updated)
   * @param lenVarSlot local variable slot containing the string length
   */
  public abstract void generateFindNextBytecode(
      MethodVisitor mv, int inputVarSlot, int startVarSlot, int lenVarSlot);

  /**
   * Estimate the speedup factor compared to charAt() loop.
   *
   * <p>Used to decide if the optimization overhead is worth it. Conservative estimates are
   * preferred to avoid false optimizations.
   *
   * @param expectedStringLength expected average string length in typical use cases
   * @return estimated speedup factor (e.g., 3.0 means 3x faster than charAt())
   */
  public abstract double estimateSpeedup(int expectedStringLength);

  /**
   * Generate bytecode to find the next matching position using a pre-created StringView.
   *
   * <p>This version eliminates the overhead of repeated StringView creation in tight loops by
   * accepting a StringView that was created once at method entry.
   *
   * <p>The generated bytecode checks if the view is usable (non-null), and falls back to the
   * String-based version if needed (for UTF-16 strings or when view is null).
   *
   * <p>Stack state before: (unchanged) Stack state after: (unchanged)
   *
   * @param mv the method visitor for bytecode generation
   * @param viewVarSlot local variable slot containing the StringView (may be null)
   * @param inputVarSlot local variable slot containing the input String
   * @param startVarSlot local variable slot containing the start position (will be updated)
   * @param lenVarSlot local variable slot containing the string length
   */
  public void generateFindNextBytecodeWithView(
      MethodVisitor mv, int viewVarSlot, int inputVarSlot, int startVarSlot, int lenVarSlot) {
    Label useStringFallback = new Label();
    Label afterOptimization = new Label();

    // if (view == null) goto useStringFallback
    mv.visitVarInsn(ALOAD, viewVarSlot);
    mv.visitJumpInsn(IFNULL, useStringFallback);

    // Fast path: use StringView
    generateFindNextBytecodeWithViewDirect(mv, viewVarSlot, startVarSlot, lenVarSlot);
    mv.visitJumpInsn(GOTO, afterOptimization);

    // Fallback: use String (for UTF-16 or when SWAR disabled)
    mv.visitLabel(useStringFallback);
    generateFindNextBytecode(mv, inputVarSlot, startVarSlot, lenVarSlot);

    mv.visitLabel(afterOptimization);
  }

  /**
   * Generate bytecode to find the next matching position using StringView directly.
   *
   * <p>This is called when we know the StringView is non-null. Subclasses implement this to call
   * the appropriate SWARHelper StringView-accepting method.
   *
   * <p>Stack state before: (unchanged) Stack state after: (unchanged)
   *
   * @param mv the method visitor for bytecode generation
   * @param viewVarSlot local variable slot containing the StringView (guaranteed non-null)
   * @param startVarSlot local variable slot containing the start position (will be updated)
   * @param lenVarSlot local variable slot containing the string length
   */
  protected abstract void generateFindNextBytecodeWithViewDirect(
      MethodVisitor mv, int viewVarSlot, int startVarSlot, int lenVarSlot);
}
