/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie;

/**
 * Public API base type for all compiled regex matchers. Subclasses are generated by the Reggie
 * compiler — either at compile time via the annotation processor or at runtime via {@code
 * Reggie.compile()} — and must not be extended manually.
 */
public abstract class ReggieMatcher {

  /** Returns {@code true} if the pattern matches the entire input string. */
  public abstract boolean matches(String input);

  /** Returns {@code true} if the pattern occurs anywhere in the input string. */
  public abstract boolean find(String input);
}
