/*
 * Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datadoghq.reggie.processor;

import static org.junit.jupiter.api.Assertions.*;

import com.datadoghq.reggie.runtime.ReggieMatcher;
import java.lang.reflect.Method;
import org.junit.jupiter.api.Test;

/**
 * End-to-end tests for bytecode generation. Tests that patterns compile to working matcher classes.
 */
class ReggiMatcherBytecodeGeneratorTest {

  @Test
  void testSimplePhonePattern() throws Exception {
    // Pattern with <50 DFA states - should use DFA_UNROLLED strategy
    String pattern = "\\d{3}-\\d{3}-\\d{4}";

    ReggiMatcherBytecodeGenerator generator =
        new ReggiMatcherBytecodeGenerator("test.generated", "PhoneMatcher", pattern);

    byte[] bytecode = generator.generate();
    assertNotNull(bytecode);
    assertTrue(bytecode.length > 0, "Generated bytecode should not be empty");

    // Load and instantiate the generated class
    TestClassLoader loader = new TestClassLoader();
    Class<?> matcherClass = loader.defineClass("test.generated.PhoneMatcher", bytecode);
    assertNotNull(matcherClass);

    // Verify it extends ReggieMatcher
    assertTrue(ReggieMatcher.class.isAssignableFrom(matcherClass));

    // Create instance
    Object matcher = matcherClass.getDeclaredConstructor().newInstance();
    assertNotNull(matcher);

    // Test matches() method
    Method matchesMethod = matcherClass.getMethod("matches", String.class);

    // Valid phone numbers
    assertTrue((Boolean) matchesMethod.invoke(matcher, "123-456-7890"));
    assertTrue((Boolean) matchesMethod.invoke(matcher, "000-000-0000"));
    assertTrue((Boolean) matchesMethod.invoke(matcher, "999-999-9999"));

    // Invalid inputs
    assertFalse((Boolean) matchesMethod.invoke(matcher, "123-456-789")); // too short
    assertFalse((Boolean) matchesMethod.invoke(matcher, "123-456-78901")); // too long
    assertFalse((Boolean) matchesMethod.invoke(matcher, "abc-def-ghij")); // letters
    assertFalse(
        (Boolean) matchesMethod.invoke(matcher, "123 456 7890")); // spaces instead of dashes

    // Null input
    assertFalse((Boolean) matchesMethod.invoke(matcher, (String) null));
  }

  @Test
  void testSimpleLiteral() throws Exception {
    // Very simple pattern - should use DFA_UNROLLED
    String pattern = "abc";

    ReggiMatcherBytecodeGenerator generator =
        new ReggiMatcherBytecodeGenerator("test.generated", "LiteralMatcher", pattern);

    byte[] bytecode = generator.generate();
    assertNotNull(bytecode);

    TestClassLoader loader = new TestClassLoader();
    Class<?> matcherClass = loader.defineClass("test.generated.LiteralMatcher", bytecode);
    Object matcher = matcherClass.getDeclaredConstructor().newInstance();

    Method matchesMethod = matcherClass.getMethod("matches", String.class);

    assertTrue((Boolean) matchesMethod.invoke(matcher, "abc"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "ab"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "abcd"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "ABC"));
  }

  @Test
  void testCharacterClass() throws Exception {
    // Pattern: [a-z]+
    String pattern = "[a-z]+";

    ReggiMatcherBytecodeGenerator generator =
        new ReggiMatcherBytecodeGenerator("test.generated", "LowerMatcher", pattern);

    byte[] bytecode = generator.generate();
    assertNotNull(bytecode);

    TestClassLoader loader = new TestClassLoader();
    Class<?> matcherClass = loader.defineClass("test.generated.LowerMatcher", bytecode);
    Object matcher = matcherClass.getDeclaredConstructor().newInstance();

    Method matchesMethod = matcherClass.getMethod("matches", String.class);

    assertTrue((Boolean) matchesMethod.invoke(matcher, "a"));
    assertTrue((Boolean) matchesMethod.invoke(matcher, "abc"));
    assertTrue((Boolean) matchesMethod.invoke(matcher, "xyz"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, ""));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "ABC"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "123"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "a1b"));
  }

  @Test
  void testFindMethod() throws Exception {
    // Pattern: \\d+
    String pattern = "\\d+";

    ReggiMatcherBytecodeGenerator generator =
        new ReggiMatcherBytecodeGenerator("test.generated", "DigitMatcher", pattern);

    byte[] bytecode = generator.generate();
    TestClassLoader loader = new TestClassLoader();
    Class<?> matcherClass = loader.defineClass("test.generated.DigitMatcher", bytecode);
    Object matcher = matcherClass.getDeclaredConstructor().newInstance();

    Method findMethod = matcherClass.getMethod("find", String.class);

    // Should find digits in these strings
    assertTrue((Boolean) findMethod.invoke(matcher, "abc123def"));
    assertTrue((Boolean) findMethod.invoke(matcher, "123"));
    assertTrue((Boolean) findMethod.invoke(matcher, "x9y"));

    // Should not find digits
    assertFalse((Boolean) findMethod.invoke(matcher, "abc"));
    assertFalse((Boolean) findMethod.invoke(matcher, "xyz"));
    assertFalse((Boolean) findMethod.invoke(matcher, ""));
  }

  @Test
  void testEmailPattern() throws Exception {
    // More complex pattern - may use DFA_SWITCH strategy
    String pattern = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}";

    ReggiMatcherBytecodeGenerator generator =
        new ReggiMatcherBytecodeGenerator("test.generated", "EmailMatcher", pattern);

    byte[] bytecode = generator.generate();
    assertNotNull(bytecode);

    TestClassLoader loader = new TestClassLoader();
    Class<?> matcherClass = loader.defineClass("test.generated.EmailMatcher", bytecode);
    Object matcher = matcherClass.getDeclaredConstructor().newInstance();

    Method matchesMethod = matcherClass.getMethod("matches", String.class);

    // Valid emails
    assertTrue((Boolean) matchesMethod.invoke(matcher, "test@example.com"));
    assertTrue((Boolean) matchesMethod.invoke(matcher, "user.name+tag@domain.co.uk"));
    assertTrue((Boolean) matchesMethod.invoke(matcher, "a@b.cc"));

    // Invalid emails
    assertFalse((Boolean) matchesMethod.invoke(matcher, "not-an-email"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "@example.com"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "test@"));
    assertFalse((Boolean) matchesMethod.invoke(matcher, "test@.com"));
  }

  /** Custom ClassLoader for loading generated bytecode in tests. */
  private static class TestClassLoader extends ClassLoader {
    public Class<?> defineClass(String name, byte[] bytecode) {
      return defineClass(name, bytecode, 0, bytecode.length);
    }
  }
}
